plugins {
    id 'com.android.application'
}

android {
    namespace 'ee.kalle.minimaltv'
    compileSdk 35
    buildToolsVersion '34.0.0'

    defaultConfig {
        applicationId 'ee.kalle.minimaltv'
        minSdk 26
        targetSdk 35
        versionCode 7
        versionName '1.5.1'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    testOptions {
        unitTests.includeAndroidResources = true
    }

    bundle {
        language {
            enableSplit = false
        }
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.robolectric:robolectric:4.14.1'
    testImplementation 'org.json:json:20240303'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}
